### ISSUE TITLE
Unparseable date when opening a MSI file

### ISSUE THREAD

**Issue by ebourg** [Jmcleodfoss/msgreader#2]
Hi,

I'm trying to use msgreader to parse a Microsoft Installer file (.msi) which is also based on the Microsoft Compound File format and I got the following exception:

    java.text.ParseException: Unparseable date: "January 1, 1601"
            at java.base/java.text.DateFormat.parse(DateFormat.java:395)
            at io.github.jmcleodfoss.msg.DataType$Time.initBaseTime(DataType.java:395)
            at io.github.jmcleodfoss.msg.DataType$Time.<clinit>(DataType.java:376)
            at io.github.jmcleodfoss.msg.DataType.<clinit>(DataType.java:435)
            at io.github.jmcleodfoss.msg.Header.<clinit>(Header.java:114)
            at io.github.jmcleodfoss.msg.MSG.<init>(MSG.java:52)

The file parsed is located here: https://github.com/ebourg/jsign/blob/3.1/jsign-core/src/test/resources/minimal.msi?raw=true

**Comment by Jmcleodfoss** [comment]
Hi Emmanuel,

That is curious - the code that throws the exception is completely
self-contained and happens before the file is processed. I cannot duplicate
this behaviour with either version 1.0.0 or version 1.0.1 of MsgExplorer
(although I get other errors on your file which appear to relate to between
the PST file format and the MSI file format). The exception you report
should only happen if there is a mismatch between the date format defined
in PST_BASE_FORMAT ("MMMM dd, yyyy") and the base date used in PST files
(January 1, 1601).

I will look into the errors I found, but I am unsure of how to proceed with
the issue you reported at this time. What environment are you running this
in? What is your locale? It looks like you are using version 1.0.0 from the
exception message; can you try the later version as well? I don't expect
any difference in behavior but it does have some useful fixes in it.

Thanks, BTW, for the pull request. I will accept it, but I want to put
together a file listing all contributors (which is you and I as of today)
first.

Regards,

James

**Comment by ebourg** [comment]
You are right the issue is locale depend. I ran the test with a french locale. With an english locale it goes further but still throws an error:

    java.lang.NullPointerException
            at io.github.jmcleodfoss.msg.Directory.getChildren(Directory.java:115)
            at io.github.jmcleodfoss.msg.NamedProperties.<init>(NamedProperties.java:50)
            at io.github.jmcleodfoss.msg.MSG.<init>(MSG.java:57)

I tried the version 1.0.0 because io.github.jmcleodfoss:msg:1.0.1 is missing from the Maven Central repository.

Thank you for thinking about crediting me for the pull request, but I don't think fixing a couple of typos is worth mentioning. That said, if all goes well I may have more significant contributions in the future. I'm looking for a replacement to Apache POI to insert entries into MSI files (to implement Authenticode signing) and msgreader looks like a promising alternative. One enhancement I will need before integrating msgreader is parsing files from memory (using a SeekableByteChannel) and not only from the filesystem.

**Comment by Jmcleodfoss** [comment]
Ah, okay. It has been a long time since I worked on this; perhaps I never
uploaded a newer version. I’ll review, and also work on the error you
reported and try to fix the locale issue.

Thanks!

James

**Comment by ebourg** [comment]
Thank you! I just tried the version 1.0.1 and got the same NullPointerException:

    java.lang.NullPointerException
        at io.github.jmcleodfoss.msg.Directory.getChildren(Directory.java:117)
        at io.github.jmcleodfoss.msg.NamedProperties.<init>(NamedProperties.java:50)
        at io.github.jmcleodfoss.msg.MSG.<init>(MSG.java:60)

**Comment by Jmcleodfoss** [comment]
I get the same error. I have opened Issue #5 for this.

**Comment by Jmcleodfoss** [comment]
Fix released today in version 1.0.3.
